### ISSUE TITLE
「カタカナひらがな」キーが反映されない

### ISSUE THREAD

**Issue by n-yuji** [n-yuji/keyboard-font#1]
```
sub ka-hiragana ta-hiragana ka-hiragana na-katakana hi-hiragana ra-hiragana ga-hiragana na-hiragana by ka_ta_ka_na-katakana_hi_ra_ga_na-hiragana;
```

となっている。
`ka`、`ta`、`ka`が`katakana`にならないといけないのだけれど……。

**Comment by monokano** [comment]
フィーチャー自動生成でそうなってしまうんですね。

新規グリフ「ka_ta_ka_na-katakana」を追加して、フィーチャー自動生成をしてみると、

> sub ka-katakana ta-katakana ka-katakana na-katakana by …

期待通りになりました。

新規グリフ「ka_ta_ka_na-katakana_na-hiragana」を追加して、自動生成をしてみると、

> sub ka-hiragana ta-hiragana ka-hiragana na-katakana na-hiragana by …

ここでおかしくなりますね。

バグかな～

**Comment by n-yuji** [comment]
むりくり`ka-katakana_ta-katakana_ka-katakana_na-katakana`と書くことは出来るんだけど、
OTF生成が出来なくなるんですよねぇ。
最悪、「カタカナ」と「ひらがな」を2つのキーに分けてもいいかと思っています。

**Comment by n-yuji** [comment]
フィーチャーを自動生成した後に、いったんチェックを外し、
手動で書き込んだら、どうやら出来ました。
どうも長い名前を使うとGlyhsの挙動が怪しくなるところがありますね。
でも、たぶんこれで大丈夫なはず。
